name: summary
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - fastapi>=0.104.1
  - uvicorn>=0.24.0
  - sqlalchemy>=2.0.23
  - psycopg2>=2.9.9
  - python-jose>=3.3.0
  - passlib>=1.7.4
  - pydantic>=2.5.2
  - alembic>=1.12.1
  - python-dotenv>=1.0.0
  - pytorch>=2.1.0
  - torchvision
  - opencv
  - transformers
  - pip
  - pip:
      - "fastapi[all]"
      - "passlib[bcrypt]"
      - "pydantic[email]"
      - "python-multipart"
      - "faster-whisper>=0.10.0"
